# Executa os modelos PROPHET
source("prophet/modelo_prophet_boaforma.R")
rm(list=ls())
source("prophet/modelo_prophet_capricho.R")
rm(list=ls())
source("prophet/modelo_prophet_guiadoestudante.R")
rm(list=ls())
source("prophet/modelo_prophet_quatrorodas.R")
rm(list=ls())
source("prophet/modelo_prophet_saude.R")
rm(list=ls())
source("prophet/modelo_prophet_superinteressante.R")
rm(list=ls())
source("prophet/modelo_prophet_veja.R")
rm(list=ls())
source("prophet/modelo_prophet_claudia.R")

# Executa os modelos STLF
source("stlf/modelo_stlf_boaforma.R")
rm(list=ls())
source("stlf/modelo_stlf_capricho.R")
rm(list=ls())
source("stlf/modelo_stlf_guiadoestudante.R")
rm(list=ls())
source("stlf/modelo_stlf_quatrorodas.R")
rm(list=ls())
source("stlf/modelo_stlf_saude.R")
rm(list=ls())
source("stlf/modelo_stlf_superinteressante.R")
rm(list=ls())
source("stlf/modelo_stlf_veja.R")
rm(list=ls())
source("stlf/modelo_stlf_claudia.R")
rm(list=ls())

# Executa os modelos SARIMA com as modelagens já feitas
source("sarima/modelo_sarima_boaforma.R")
rm(list=ls())
source("sarima/modelo_sarima_capricho.R")
rm(list=ls())
source("sarima/modelo_sarima_guiadoestudante.R")
rm(list=ls())
source("sarima/modelo_sarima_quatrorodas.R")
rm(list=ls())
source("sarima/modelo_sarima_saude.R")
rm(list=ls())
source("sarima/modelo_sarima_superinteressante.R")
rm(list=ls())
source("sarima/modelo_sarima_veja.R")
rm(list=ls())
source("sarima/modelo_sarima_claudia.R")
rm(list=ls())

# Execução dos modelos Ensemble
source("ensemble/modelo_ensemble_boaforma.R")
rm(list=ls())
source("ensemble/modelo_ensemble_capricho.R")
rm(list=ls())
source("ensemble/modelo_ensemble_guiadoestudante.R")
rm(list=ls())
source("ensemble/modelo_ensemble_quatrorodas.R")
rm(list=ls())
source("ensemble/modelo_ensemble_saude.R")
rm(list=ls())
source("ensemble/modelo_ensemble_superinteressante.R")
rm(list=ls())
source("ensemble/modelo_ensemble_veja.R")
rm(list=ls())
source("ensemble/modelo_ensemble_claudia.R")
rm(list=ls())

# Tabela de previsão consolidada
source("5.1.tabela_previsao_consolidada_boaforma.R")
rm(list=ls())
source("5.2.tabela_previsao_consolidada_capricho.R")
rm(list=ls())
source("5.3.tabela_previsao_consolidada_guiadoestudante.R")
rm(list=ls())
source("5.4.tabela_previsao_consolidada_quatrorodas.R")
rm(list=ls())
source("5.5.tabela_previsao_consolidada_saude.R")
rm(list=ls())
source("5.6.tabela_previsao_consolidada_superinteressante.R")
rm(list=ls())
source("5.7.tabela_previsao_consolidada_veja.R")
rm(list=ls())
source("5.8.tabela_previsao_consolidada_claudia.R")
rm(list=ls())